export type TranslationKey =
    | 'cancel'
    | 'confirm'
    | 'save'
    | '404'
    | "all"
    | 'other'
    | 'bookmarked'
    | 'notFullySupported'

    | 'settings.language'

    | 'nav.menu'
    | 'nav.guestWelcome'
    | 'nav.pleaseLogin'
    | 'nav.login'
    | 'nav.logOut'

    | 'search.genericDialogue'

    | 'sidebar.personas'
    | 'sidebar.underwriter'
    | 'sidebar.businessAnalyst'
    | 'sidebar.actuarialAnalyst'
    | 'sidebar.exlOperations'
    | 'sidebar.businessOperations'
    | 'sidebar.home'
    | 'sidebar.dashboard'
    | 'sidebar.manageContent'
    | 'sidebar.contentLibrary'
    | 'sidebar.bulkUpload'
    | 'sidebar.addContent'
    | 'sidebar.addEmployees'
    | 'sidebar.viewEmployees'
    | 'sidebar.manageEmployees'
    | 'sidebar.team'
    | 'sidebar.servicereqs'

    | 'footer.ContentManager'
    | 'footer.rightsReserved'
    | 'footer.notice'
    | 'footer.WPI'

    | 'themes'

    | 'role.lead'
    | 'role.assistantLead'
    | 'role.assistantLeadAndScrumMaster'
    | 'role.fullTime'
    | 'role.ptManager'
    | 'role.ptOwner'
    | 'role.ptAnalyst'

    | 'home.header'
    | 'home.subheader'
    | 'home.mainHeader'
    | 'home.subHeader'
    | 'home.disclaimer'
    | 'home.appBy'
    | 'home.studentProject'
    | 'home.meetTheTeam'
    | 'home.notLoggedIn'
    | 'home.manageFiles'
    | 'home.bubble1'
    | 'home.bubble2'
    | 'home.bubble3'

    | 'status'
    | 'status.new'
    | 'status.inProgress'
    | 'status.complete'

    | 'kind'
    | 'kind.reference'
    | 'kind.workflow'

    | 'persona'
    | 'persona.underwriter'
    | 'persona.businessAnalyst'
    | 'persona.actuarialAnalyst'
    | 'persona.excelOperator'
    | 'persona.businessOps'
    | 'persona.admin'

    | 'file.type'
    | 'file.pdf'
    | 'file.document'
    | 'file.spreadsheet'
    | 'file.presentation'
    | 'file.image'
    | 'file.audio'
    | 'file.video'
    | 'file.archive'
    | 'file.code'
    | 'file.other'
    | 'file.link'

    | 'item'
    | 'of'
    | 'page'
    | 'pages.rowsPerPage'

    | 'disclaimer.start'
    | 'disclaimer.middle'
    | 'disclaimer.end'

    | 'dashboard.subtitle'
    | 'dashCard.myFiles'
    | 'dashCard.timeItIs'
    | 'dashCard.timeOn'
    | 'dashCard.ContentBreakdown'
    | 'dashCard.ContentDistribution'
    | 'dashCard.DepartmentBreakdown'
    | 'dashCard.DepartmentHeadcount'
    | 'dashCard.WelcomeBack'
    | 'dashCard.LetsPickUp'
    | 'dashCard.AdditionalLinks'
    | 'dashCard.RecentlyViewed'
    | 'dashCard.ViewFiles'
    | 'dashCard.RecentFiles'
    | 'dashCard.QuickLinks'
    | 'dashCard.ViewCalendar'
    | 'dashCard.LoadingReport'
    | 'dashCard.Reports'
    | 'dashCard.loadFail'
    | 'dashCard.ReportsAndAnalytics'
    | 'dashCard.reports.Subtitle'
    | 'dashCard.reports.infoButton'

    | 'customize'
    | 'customize.title'
    | 'customize.subtitle'

    | 'content'
    | 'content.filters'
    | 'content.hide'
    | 'content.forYou'
    | 'content.ownedByMe'
    | 'content.favorites'
    | 'content.favorite'
    | 'content.deleteConfirmation'
    | 'content.cannotBeUndone'
    | 'content.deleteDialogue'
    | 'content.view'
    | 'content.description'
    | 'content.name'
    | 'content.actions'
    | 'content.owner'
    | 'content.checkout'
    | 'content.checkoutTitle'
    | 'content.checkoutDesc1'
    | 'content.checkoutDesc2';

